// examples/svelte/src/lib/DebugHud.svelte
<script lang="ts">
  import {focusedNode} from './dpad';
</script>

<div class="debug-hud glass-panel mono" class:visible={$focusedNode}>
  <div><span class="dot"></span><b>SPATIAL NODE ACTIVE</b></div>
  <div class="row">ID: <b>{$focusedNode?.id ?? 'none'}</b></div>
  <div class="row">TABINDEX: <b>{$focusedNode?.tabindex ?? 0}</b></div>
  <div class="row">COORDS: <b>{$focusedNode ? `${$focusedNode.x}, ${$focusedNode.y}` : '0, 0'}</b></div>
</div>

// examples/react/src/lib/DebugHud.tsx
import {useFocusedNode} from './dpad';

export default function DebugHud() {
  const node = useFocusedNode();

  return (
    <div className={`debug-hud glass-panel mono${node ? ' visible' : ''}`}>
      <div>
        <span className="dot" />
        <b>SPATIAL NODE ACTIVE</b>
      </div>
      <div className="row">
        ID: <b>{node?.id ?? 'none'}</b>
      </div>
      <div className="row">
        TABINDEX: <b>{node?.tabindex ?? 0}</b>
      </div>
      <div className="row">
        COORDS: <b>{node ? `${node.x}, ${node.y}` : '0, 0'}</b>
      </div>
    </div>
  );
}
