// examples/react/src/lib/TopBar.tsx
import {toggleDebug, useDebugOn} from './dpad';

export default function TopBar() {
  const debugOn = useDebugOn();

  return (
    <header className="top-bar">
      <h1>SpatialExplorer</h1>
      <div className="top-bar-actions">
        <div className="search-box">
          <span className="material-symbols-outlined">search</span>
          <span>Search...</span>
        </div>
        <button
          className={`dpad-focusable icon-btn${debugOn ? ' active' : ''}`}
          tabIndex={0}
          data-node-id="debug-toggle"
          onClick={toggleDebug}
          title="Toggle debug vectors"
        >
          <span className="material-symbols-outlined">bug_report</span>
        </button>
        <button className="dpad-focusable icon-btn" tabIndex={0} data-node-id="account" aria-label="Account">
          <span className="material-symbols-outlined">account_circle</span>
        </button>
      </div>
    </header>
  );
}

// examples/svelte/src/lib/TopBar.svelte
<script lang="ts">
  import {toggleDebug, debugOn} from './dpad';
</script>

<header class="top-bar">
  <h1>SpatialExplorer</h1>
  <div class="top-bar-actions">
    <div class="search-box">
      <span class="material-symbols-outlined">search</span>
      <span>Search...</span>
    </div>
    <button
      class="dpad-focusable icon-btn"
      class:active={$debugOn}
      tabindex="0"
      data-node-id="debug-toggle"
      onclick={toggleDebug}
      title="Toggle debug vectors"
    >
      <span class="material-symbols-outlined">bug_report</span>
    </button>
    <button class="dpad-focusable icon-btn" tabindex="0" data-node-id="account" aria-label="Account">
      <span class="material-symbols-outlined">account_circle</span>
    </button>
  </div>
</header>
